
name: Build / Release / Benchmark

# Build on each commit
# Gasmodel and release must be manually selected.
on:

  schedule:
    - cron: '36 4 * * *'

  workflow_dispatch:
    inputs:

      cleanup:
        description: 'Delete cache : Build from scratch'
        type: boolean
        default: false

      gasmodel:
          description: "Run Gasmodel"
          type: boolean
          required: true
          default: false

      release:
          description: "Create a github release (Only Draft)"
          type: boolean
          required: true
          default: false

      commit_sha:
        description: "Commit to build.. Empty to build the tip"
        type: string
        required: false

      version_suffix:
        description: "Optional Suffix for the vesion number (eg beta)"
        type: string
        required: false
        default: ""


  push:
    paths:
    - '**'
    - '!.github/**'
    - '.github/workflows/applications.yml'

jobs:

  cleanup:
    if: github.event_name == 'schedule' || inputs.cleanup
    runs-on: ubuntu-latest

    permissions:
      actions: write
      contents: read

    steps:
      - name: Delete caches
        run: gh cache delete --all --repo "$GITHUB_REPOSITORY"
        env:
          GH_TOKEN: ${{ github.token }}


  build:
    needs: cleanup
    if: always()
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        ghc: ["9.8.2", "9.10.3"]
        cabal: ["3.12"]
        os: ["ubuntu-22.04", "ubuntu-24.04", "macos-14", "macos-15"]
        cabalcache: ["true"]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v6
      with:
          ref: ${{ inputs.commit_sha || github.sha }}

    # Needed for a certain test
    - name: Download chain9 test file
      run: |
        mkdir -p pact-tests/legacy-db-regression
        curl -L https://raw.githubusercontent.com/kda-community/test-fixtures/refs/heads/main/pact-v1-chain-9.sqlite.xz | unxz > pact-tests/legacy-db-regression/pact-v1-chain-9.sqlite

    # Haskell Setup
    - name: Set permissions for .ghcup (ubuntu)
      if: startsWith(matrix.os, 'ubuntu-')
      run: sudo chown -R $USER /usr/local/.ghcup
    - name: Install GHC and Cabal
      uses: haskell-actions/setup@v2
      with:
         ghc-version: ${{ matrix.ghc }}
         cabal-version: ${{ matrix.cabal }}
    - name: Confirm GHC and Cabal installation
      run: |
        ghc --version
        cabal --version

    - name: Setting up MPFR (Ubuntu)
      if: startsWith(matrix.os, 'ubuntu-')
      shell: bash
      run: sudo apt-get update && sudo apt-get install -y libmpfr-dev

    # Project Setup
    - name: Create cabal.project.local
      shell: bash
      run: |
        cat > cabal.project.local <<EOF
        documentation: False
        package pact
          tests: True
          benchmarks: True
          documentation: False
          optimization: 1
          flags: ${{ matrix.flags }} +cryptonite-ed25519
        extra-include-dirs:
          /opt/local/include
          /usr/local/opt/openssl/include
        extra-lib-dirs:
          /opt/local/lib
          /usr/local/opt/openssl/lib/
        EOF

    - name: Add check for unused packages
      shell: bash
      run: |
        cat >> cabal.project.local <<EOF
        package pact
          ghc-options: -Wunused-packages
        EOF

    - name: Print cabal.project.local
      shell: bash
      run: cat cabal.project.local

    # Build
    - name: Update package database
      shell: bash
      run: cabal update

    - name: Configure build / and freeze
      run: |
        cabal build --dry-run
        cabal freeze

    - name: Generate cache key
      id: cache-key
      run: |
        grep -v '^index-state:' cabal.project.freeze > freeze-deps-only
        FREEZE_HASH=$(shasum freeze-deps-only | cut -d' ' -f1)
        echo "freeze-hash=$FREEZE_HASH" >> $GITHUB_OUTPUT
        rm freeze-deps-only

    - name: Restore Cabal store
      id: restore-cabal
      uses: actions/cache/restore@v5
      with:
        path: ~/.cabal/store
        key: cabal-${{ matrix.os }}-${{ matrix.ghc }}-${{ steps.cache-key.outputs.freeze-hash }}
        restore-keys: |
          cabal-${{ matrix.os }}-${{ matrix.ghc }}

    - name: Display outdated packages
      run: cabal outdated

    - name: Build dependencies
      if: steps.restore-cabal.outputs.cache-hit != 'true'
      shell: bash
      run: cabal build --only-dependencies

    - name: Cache Cabal store if necessary
      if: steps.restore-cabal.outputs.cache-hit != 'true'
      uses: actions/cache/save@v5
      with:
        path: ~/.cabal/store
        key: cabal-${{ matrix.os }}-${{ matrix.ghc }}-${{ steps.cache-key.outputs.freeze-hash }}

    - name: Build
      shell: bash
      run: cabal build

    - name: Test
      shell: bash
      run: cabal run tests -- --hedgehog-discards 200

    - name: Verify Binary Linking
      shell: bash
      if: "!contains(matrix.flags, '-build-tool')"
      run: cabal run exe:pact -- --version

    # Publish Artifacts
    - name: Prepare artifacts
      if: "!contains(matrix.flags, '-build-tool')"
      shell: bash
      run: |

        OUTPUT_DIR=artifacts/pact
        mkdir -p $OUTPUT_DIR
        mkdir -p $OUTPUT_DIR/gasmodel/contracts/
        cp $(cabal list-bin pact) $OUTPUT_DIR
        cp $(cabal list-bin profile-tx) $OUTPUT_DIR
        cp $(cabal list-bin core-tests) $OUTPUT_DIR
        cp $(cabal list-bin gasmodel) $OUTPUT_DIR/run_gasmodel
        cp CHANGELOG.md $OUTPUT_DIR
        cp README.md $OUTPUT_DIR
        cp LICENSE $OUTPUT_DIR
        cp pact-tng.cabal artifacts/pact
        cp cabal.project artifacts/pact
        cp cabal.project.local artifacts/pact
        cp cabal.project.freeze artifacts/pact
        cp gasmodel/contracts/coin-v5-create.pact $OUTPUT_DIR/gasmodel/contracts/

        OUTPUT_DIR=artifacts/pact_to_release
        mkdir -p $OUTPUT_DIR
        cp $(cabal list-bin pact) $OUTPUT_DIR
        strip $OUTPUT_DIR/pact
        cp CHANGELOG.md $OUTPUT_DIR
        cp README.md $OUTPUT_DIR
        cp LICENSE $OUTPUT_DIR

    - name: Publish applications
      if: "!contains(matrix.flags, '-build-tool')"
      uses: actions/upload-artifact@v7
      with:
        name: pact-applications.${{ matrix.ghc }}.${{ matrix.os }}
        path: artifacts/pact

    - name: Publish release artifact
      if: "!contains(matrix.flags, '-build-tool')"
      uses: actions/upload-artifact@v7
      with:
        name: pact-to-release.ghc${{ matrix.ghc }}.${{ matrix.os }}
        path: artifacts/pact_to_release


  release:

    runs-on: "ubuntu-latest"
    needs: build
    if: always() && inputs.release == true

    env:
      GHC_FOR_RELEASE: "9.10.3"
      OS_TO_RELEASE: "ubuntu-22.04 ubuntu-24.04 macos-14 macos-15"
      MAIN_LINUX_VERSION: "ubuntu-24.04"

    strategy:
      fail-fast: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          ref: ${{ inputs.commit_sha || github.sha }}

      - name: Download artifacts
        uses : actions/download-artifact@v8
        with:
          pattern: pact-to-release.ghc${{ env.GHC_FOR_RELEASE }}.*
          path: to_release/

      - name: List directory
        shell: bash
        run: ls -lR to_release

      - name: Retrieve version
        id: get_version
        shell: bash
        run: |
          PACT_BIN=to_release/pact-to-release.ghc${{ env.GHC_FOR_RELEASE }}.${{ env.MAIN_LINUX_VERSION }}/pact
          chmod a+x "$PACT_BIN"
          VERSION=$($PACT_BIN --version | grep -oE '[0-9]+(\.[0-9]+)+')${{inputs.version_suffix}}
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Prepare releases
        id: prepare
        shell: bash
        run: |
          mkdir -p releases_archives

          for o in $OS_TO_RELEASE
          do FILENAME=pact-${{ steps.get_version.outputs.version }}-${GITHUB_SHA::4}-$o.tar.gz
             SRC_DIR=to_release/pact-to-release.ghc${{ env.GHC_FOR_RELEASE }}.$o
             chmod a+x $SRC_DIR/pact
             (cd $SRC_DIR; tar czf $GITHUB_WORKSPACE/releases_archives/$FILENAME *)
          done

      - name: List directory
        shell: bash
        run: ls -lR releases_archives

      - name: Generate release
        uses: ncipollo/release-action@v1

        with:
          bodyFile: .github/RELEASE.md
          artifacts: releases_archives/*
          commit: ${{ inputs.commit_sha || github.sha }}
          name: Pact v${{ steps.get_version.outputs.version }}
          tag: ${{ steps.get_version.outputs.version }}
          token: ${{ secrets.GH_PAT }}
          prerelease: true
          omitBodyDuringUpdate: true
          skipIfReleaseExists: false
          draft: false
          generateReleaseNotes: true
          allowUpdates: true
          replacesArtifacts: true
          updateOnlyUnreleased: true

  gasmodel:
    runs-on: "ubuntu-24.04"
    needs: build
    if: always() && inputs.gasmodel == true

    env:
      GHC_FOR_BENCHMARKS: "9.10.3"
      OS_FOR_BENCHMARKS: "ubuntu-24.04"
      criterion_datadir: ${{ github.workspace }}/html-data
      js_chart_datadir: ${{ github.workspace }}/html-data

    steps:
      - name: Download artifacts
        uses : actions/download-artifact@v5
        with:
          pattern: pact-applications.${{ env.GHC_FOR_BENCHMARKS }}.${{ env.OS_FOR_BENCHMARKS }}
          path: pact_apps

      - name: Download Criterion templates
        run: |
          mkdir -p $criterion_datadir/templates
          cd $criterion_datadir/templates
          wget https://raw.githubusercontent.com/haskell/criterion/refs/heads/master/templates/criterion.css
          wget https://raw.githubusercontent.com/haskell/criterion/refs/heads/master/templates/criterion.js
          wget https://raw.githubusercontent.com/haskell/criterion/refs/heads/master/templates/default.tpl
          wget https://raw.githubusercontent.com/haskell/criterion/refs/heads/master/templates/json.tpl

          cd ${js_chart_datadir}
          wget  https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.4/Chart.min.js
          wget  https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.4/Chart.min.css


      - name: List directory
        shell: bash
        run: ls -lR .

      - name: Run gasmodel
        run: |
          mkdir -p results
          cd pact_apps
          chmod +x run_gasmodel
          ./run_gasmodel -o ../results/gasmodel_results.html --json ../results/gasmodel_results.json --csv ../results/gasmodel_results.csv

      - name: Publish Gasmodel
        uses: actions/upload-artifact@v7
        with:
          name: gasmodel
          path: results
